#!/bin/bash
set -euo pipefail

# Test kmod build from generated spec in Fedora container
# This script tests building kmod packages from the kmod spec generated by akmod build

echo "=== Starting Fedora container test for kmod build ==="

# Get current directory for Docker mount
WORKSPACE_DIR="$(pwd)"

# Run all tests in a Fedora container
docker run --rm -v "${WORKSPACE_DIR}:/workspace" -w /workspace fedora:latest bash -c '
set -euo pipefail

echo "=== Installing build dependencies ==="
dnf install -y rpm-build rpmdevtools kmodtool kernel-devel gcc make spectool

echo "=== Setting up RPM build tree ==="
rpmdev-setuptree

echo "=== Copying akmod spec file ==="
cp /workspace/specs/akmod-maccel.spec ~/rpmbuild/SPECS/

echo "=== Downloading source with spectool ==="
spectool -g -R ~/rpmbuild/SPECS/akmod-maccel.spec

echo "=== Building akmod package to generate kmod spec ==="
rpmbuild --define "version 0.5.6" --define "release 1" --nodeps --noclean -ba ~/rpmbuild/SPECS/akmod-maccel.spec

echo ""
echo "=== Locating generated kmod spec from akmod build ==="
KMOD_SPEC=$(find ~/rpmbuild/BUILD -name "kmod-maccel.spec" | head -1)
if [ -z "$KMOD_SPEC" ]; then
    echo "✗ Generated kmod spec NOT found in ~/rpmbuild/BUILD/"
    echo "Available BUILD directories:"
    ls -la ~/rpmbuild/BUILD/ || true
    exit 1
fi
echo "✓ Found generated kmod spec: $KMOD_SPEC"

echo ""
echo "=== Copying generated kmod spec to ~/rpmbuild/SPECS/ ==="
cp "$KMOD_SPEC" ~/rpmbuild/SPECS/
echo "✓ Copied to ~/rpmbuild/SPECS/kmod-maccel.spec"

echo ""
echo "=== Getting kernel version ==="
KVER=$(rpm -q kernel-devel --queryformat '\''%{VERSION}-%{RELEASE}\n'\'' | head -1)
echo "✓ Kernel version: $KVER"

echo ""
echo "=== Building kmod package ==="
echo "Command: rpmbuild --define \"kernels $KVER\" -ba ~/rpmbuild/SPECS/kmod-maccel.spec"
rpmbuild --define "kernels $KVER" -ba ~/rpmbuild/SPECS/kmod-maccel.spec

echo ""
echo "=== Listing built kmod packages ==="
ls -la ~/rpmbuild/RPMS/x86_64/kmod-maccel* || {
    echo "✗ No kmod packages found"
    echo "Checking all RPMS:"
    find ~/rpmbuild/RPMS -name "*.rpm" -ls
    exit 1
}

echo ""
echo "=== Verifying kmod meta-package is created ==="
META_PKG=$(find ~/rpmbuild/RPMS -name "kmod-maccel-[0-9]*.rpm" ! -name "*${KVER}*" | head -1)
if [ -n "$META_PKG" ]; then
    echo "✓ Meta-package found: $(basename "$META_PKG")"
    echo "  Contents:"
    rpm -qlp "$META_PKG"
else
    echo "⚠ Meta-package not found (may be expected depending on kmodtool version)"
fi

echo ""
echo "=== Verifying kernel-specific package naming includes full kernel version ==="
KERNEL_PKG=$(find ~/rpmbuild/RPMS -name "kmod-maccel-*${KVER}*.rpm" | head -1)
if [ -z "$KERNEL_PKG" ]; then
    echo "✗ Kernel-specific package NOT found with kernel version in filename"
    echo "Available packages:"
    find ~/rpmbuild/RPMS -name "kmod-maccel*.rpm" -ls
    exit 1
fi
echo "✓ Kernel-specific package found: $(basename "$KERNEL_PKG")"

echo ""
echo "=== Verifying kmod package creates per-kernel subpackages ==="
echo "Package contents:"
rpm -qlp "$KERNEL_PKG"

echo ""
echo "=== Verifying kernel module is in correct location ==="
if rpm -qlp "$KERNEL_PKG" | grep -q "/lib/modules/${KVER}/extra/maccel/maccel.ko"; then
    echo "✓ Kernel module found in correct location: /lib/modules/${KVER}/extra/maccel/maccel.ko"
elif rpm -qlp "$KERNEL_PKG" | grep -q "/lib/modules/${KVER}.*maccel.ko"; then
    echo "✓ Kernel module found in kernel-specific path"
    rpm -qlp "$KERNEL_PKG" | grep "maccel.ko"
else
    echo "✗ Kernel module NOT found in expected location"
    echo "Package contents:"
    rpm -qlp "$KERNEL_PKG"
    exit 1
fi

echo ""
echo "=== Verifying package metadata ==="
echo "Package info:"
rpm -qip "$KERNEL_PKG" | head -20

echo ""
echo "=== All verification checks passed! ==="
echo ""
echo "Summary:"
echo "  ✓ Generated kmod spec located from akmod build"
echo "  ✓ Kmod spec copied to ~/rpmbuild/SPECS/"
echo "  ✓ Kernel version detected: $KVER"
echo "  ✓ Kmod package built successfully"
echo "  ✓ Kernel-specific package created with full kernel version in filename"
echo "  ✓ Per-kernel subpackage verified"
echo "  ✓ Kernel module in correct location"
'

echo ""
echo "=== Test completed successfully ==="
