# kmod-maccel.spec - Kernel module package for maccel mouse acceleration driver
#
# NOTE: This spec file is a STUB for future use and is NOT used in automated builds.
#
# This spec file is designed to be generated by kmodtool from the akmod-maccel package.
# In the current implementation, only the akmod-maccel package is built automatically.
# The akmod package handles kernel module building dynamically when kernels are updated.
#
# FUTURE ENHANCEMENT:
# This spec could be used to build pre-compiled kmod packages for specific kernel versions
# if there is a need to distribute kernel-specific binary modules. This would be useful for:
# - Systems where akmods cannot run (e.g., immutable systems, containers)
# - Faster installation without compilation
# - Distribution through repositories that prefer binary kmods
#
# To generate kmod packages from akmod-maccel in the future:
#   kmodtool --target x86_64 --kmodname maccel --filterfile /dev/null \
#            --for-kernels "$(uname -r)" --devel /usr/src/kernels/$(uname -r) \
#            akmod-maccel.spec > kmod-maccel.spec
#
# Then build with:
#   rpmbuild -bb kmod-maccel.spec

%define debug_package %{nil}

# Kernel version placeholder - would be set by kmodtool
# For stub purposes, use a placeholder that won't cause parse errors
%define kversion %{?kernel_version}%{!?kernel_version:0.0.0}

Name:           kmod-maccel
Version:        %(echo "${MACCEL_VERSION:-0.0.0}" | sed 's/^v//')
Release:        1%{?dist}
Summary:        Kernel module for maccel mouse acceleration driver (kernel %{kversion})

License:        GPL-2.0-or-later
URL:            https://github.com/Gnarus-G/maccel
Source0:        https://github.com/Gnarus-G/maccel/archive/v%{version}/maccel-%{version}.tar.gz

BuildRequires:  kernel-devel
BuildRequires:  gcc
BuildRequires:  make

Requires:       kernel

Provides:       kmod-maccel = %{version}-%{release}

%description
This package provides the maccel kernel module compiled for kernel version %{kversion}.

Maccel is a mouse acceleration driver for Linux that provides customizable mouse
acceleration curves and parameters through a kernel module and CLI tool.

NOTE: This is a stub spec file for future use. The recommended installation method
is to use the akmod-maccel package, which automatically rebuilds the kernel module
when the kernel is updated.

%prep
# Error out if the version is not set
if [ "%{version}" = "0.0.0" ]; then
    echo "ERROR: MACCEL_VERSION environment variable not set"
    exit 1
fi

%setup -q -n maccel-%{version}

%build
# Build the kernel module for the specific kernel version
cd driver

# Set FIXEDPT_BITS=64 for x86_64 architecture
%if "%{_target_cpu}" == "x86_64"
export CFLAGS_MODULE="-DFIXEDPT_BITS=64"
%endif

# Build the module
# Note: In actual use, kmodtool would set the proper kernel source path
make -C %{?kernel_source}%{!?kernel_source:/usr/src/kernels/%{kversion}} M=$(pwd) modules

%install
# Install the compiled kernel module
mkdir -p %{buildroot}%{?kernel_module_package_moddir}%{!?kernel_module_package_moddir:/lib/modules/%{kversion}/extra}/maccel/
install -m 644 driver/maccel.ko %{buildroot}%{?kernel_module_package_moddir}%{!?kernel_module_package_moddir:/lib/modules/%{kversion}/extra}/maccel/

%post
# Run depmod to update module dependencies
/sbin/depmod -a || true

# Load the module
echo "Loading maccel kernel module..."
/sbin/modprobe maccel || true

%preun
# Unload the module before uninstallation
if [ $1 -eq 0 ]; then
    if /sbin/lsmod | grep -q maccel; then
        echo "Unloading maccel kernel module..."
        /sbin/modprobe -r maccel || true
    fi
fi

%postun
# Run depmod to update module dependencies after removal
if [ $1 -eq 0 ]; then
    /sbin/depmod -a || true
fi

%files
%{?kernel_module_package_moddir}%{!?kernel_module_package_moddir:/lib/modules/%{kversion}/extra}/maccel/maccel.ko

%changelog
# Changelog entries will be generated during build
# See https://github.com/Gnarus-G/maccel/releases for upstream changes
